version: '3.8'
services:
    postgres:
        image: postgres:14.4
        restart: always
        environment:
          - POSTGRES_USER=viper
          - POSTGRES_PASSWORD=viper
          - POSTGRES_DB=visdb
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./pgdata:/var/lib/postgresql/pgdata
